// https://docs.arangodb.com/3.4/Manual/Appendix/ErrorCodes.html
// https://github.com/arangodb/arangodb/blob/devel/lib/Basics/errors.dat

// replace `    (\w*),(\d*),.*` by `export const $1 = $2;`

// General errors
export const ERROR_NO_ERROR = 0;
export const ERROR_FAILED = 1;
export const ERROR_SYS_ERROR = 2;
export const ERROR_OUT_OF_MEMORY = 3;
export const ERROR_INTERNAL = 4;
export const ERROR_ILLEGAL_NUMBER = 5;
export const ERROR_NUMERIC_OVERFLOW = 6;
export const ERROR_ILLEGAL_OPTION = 7;
export const ERROR_DEAD_PID = 8;
export const ERROR_NOT_IMPLEMENTED = 9;
export const ERROR_BAD_PARAMETER = 10;
export const ERROR_FORBIDDEN = 11;
export const ERROR_OUT_OF_MEMORY_MMAP = 12;
export const ERROR_CORRUPTED_CSV = 13;
export const ERROR_FILE_NOT_FOUND = 14;
export const ERROR_CANNOT_WRITE_FILE = 15;
export const ERROR_CANNOT_OVERWRITE_FILE = 16;
export const ERROR_TYPE_ERROR = 17;
export const ERROR_LOCK_TIMEOUT = 18;
export const ERROR_CANNOT_CREATE_DIRECTORY = 19;
export const ERROR_CANNOT_CREATE_TEMP_FILE = 20;
export const ERROR_REQUEST_CANCELED = 21;
export const ERROR_DEBUG = 22;
export const ERROR_IP_ADDRESS_INVALID = 25;
export const ERROR_FILE_EXISTS = 27;
export const ERROR_LOCKED = 28;
export const ERROR_DEADLOCK = 29;
export const ERROR_SHUTTING_DOWN = 30;
export const ERROR_ONLY_ENTERPRISE = 31;
export const ERROR_RESOURCE_LIMIT = 32;
export const ERROR_ARANGO_ICU_ERROR = 33;
export const ERROR_CANNOT_READ_FILE = 34;
export const ERROR_INCOMPATIBLE_VERSION = 35;
export const ERROR_DISABLED = 36;

// HTTP error status codes
export const ERROR_HTTP_BAD_PARAMETER = 400;
export const ERROR_HTTP_UNAUTHORIZED = 401;
export const ERROR_HTTP_FORBIDDEN = 403;
export const ERROR_HTTP_NOT_FOUND = 404;
export const ERROR_HTTP_METHOD_NOT_ALLOWED = 405;
export const ERROR_HTTP_NOT_ACCEPTABLE = 406;
export const ERROR_HTTP_PRECONDITION_FAILED = 412;
export const ERROR_HTTP_SERVER_ERROR = 500;
export const ERROR_HTTP_SERVICE_UNAVAILABLE = 503;
export const ERROR_HTTP_GATEWAY_TIMEOUT = 504;

// HTTP processing errors
export const ERROR_HTTP_CORRUPTED_JSON = 600;
export const ERROR_HTTP_SUPERFLUOUS_SUFFICES = 601;

// Internal ArangoDB storage errors
// For errors that occur because of a programming error.
export const ERROR_ARANGO_ILLEGAL_STATE = 1000;
export const ERROR_ARANGO_DATAFILE_SEALED = 1002;
export const ERROR_ARANGO_READ_ONLY = 1004;
export const ERROR_ARANGO_DUPLICATE_IDENTIFIER = 1005;
export const ERROR_ARANGO_DATAFILE_UNREADABLE = 1006;
export const ERROR_ARANGO_DATAFILE_EMPTY = 1007;
export const ERROR_ARANGO_RECOVERY = 1008;
export const ERROR_ARANGO_DATAFILE_STATISTICS_NOT_FOUND = 1009;

// External ArangoDB storage errors
// For errors that occur because of an outside event.
export const ERROR_ARANGO_CORRUPTED_DATAFILE = 1100;
export const ERROR_ARANGO_ILLEGAL_PARAMETER_FILE = 1101;
export const ERROR_ARANGO_CORRUPTED_COLLECTION = 1102;
export const ERROR_ARANGO_MMAP_FAILED = 1103;
export const ERROR_ARANGO_FILESYSTEM_FULL = 1104;
export const ERROR_ARANGO_NO_JOURNAL = 1105;
export const ERROR_ARANGO_DATAFILE_ALREADY_EXISTS = 1106;
export const ERROR_ARANGO_DATADIR_LOCKED = 1107;
export const ERROR_ARANGO_COLLECTION_DIRECTORY_ALREADY_EXISTS = 1108;
export const ERROR_ARANGO_MSYNC_FAILED = 1109;
export const ERROR_ARANGO_DATADIR_UNLOCKABLE = 1110;
export const ERROR_ARANGO_SYNC_TIMEOUT = 1111;

// General ArangoDB storage errors
// For errors that occur when fulfilling a user request.
export const ERROR_ARANGO_CONFLICT = 1200;
export const ERROR_ARANGO_DATADIR_INVALID = 1201;
export const ERROR_ARANGO_DOCUMENT_NOT_FOUND = 1202;
export const ERROR_ARANGO_DATA_SOURCE_NOT_FOUND = 1203;
export const ERROR_ARANGO_COLLECTION_PARAMETER_MISSING = 1204;
export const ERROR_ARANGO_DOCUMENT_HANDLE_BAD = 1205;
export const ERROR_ARANGO_MAXIMAL_SIZE_TOO_SMALL = 1206;
export const ERROR_ARANGO_DUPLICATE_NAME = 1207;
export const ERROR_ARANGO_ILLEGAL_NAME = 1208;
export const ERROR_ARANGO_NO_INDEX = 1209;
export const ERROR_ARANGO_UNIQUE_CONSTRAINT_VIOLATED = 1210;
export const ERROR_ARANGO_INDEX_NOT_FOUND = 1212;
export const ERROR_ARANGO_CROSS_COLLECTION_REQUEST = 1213;
export const ERROR_ARANGO_INDEX_HANDLE_BAD = 1214;
export const ERROR_ARANGO_DOCUMENT_TOO_LARGE = 1216;
export const ERROR_ARANGO_COLLECTION_NOT_UNLOADED = 1217;
export const ERROR_ARANGO_COLLECTION_TYPE_INVALID = 1218;
export const ERROR_ARANGO_VALIDATION_FAILED = 1219;
export const ERROR_ARANGO_ATTRIBUTE_PARSER_FAILED = 1220;
export const ERROR_ARANGO_DOCUMENT_KEY_BAD = 1221;
export const ERROR_ARANGO_DOCUMENT_KEY_UNEXPECTED = 1222;
export const ERROR_ARANGO_DATADIR_NOT_WRITABLE = 1224;
export const ERROR_ARANGO_OUT_OF_KEYS = 1225;
export const ERROR_ARANGO_DOCUMENT_KEY_MISSING = 1226;
export const ERROR_ARANGO_DOCUMENT_TYPE_INVALID = 1227;
export const ERROR_ARANGO_DATABASE_NOT_FOUND = 1228;
export const ERROR_ARANGO_DATABASE_NAME_INVALID = 1229;
export const ERROR_ARANGO_USE_SYSTEM_DATABASE = 1230;
export const ERROR_ARANGO_ENDPOINT_NOT_FOUND = 1231;
export const ERROR_ARANGO_INVALID_KEY_GENERATOR = 1232;
export const ERROR_ARANGO_INVALID_EDGE_ATTRIBUTE = 1233;
export const ERROR_ARANGO_INDEX_DOCUMENT_ATTRIBUTE_MISSING = 1234;
export const ERROR_ARANGO_INDEX_CREATION_FAILED = 1235;
export const ERROR_ARANGO_WRITE_THROTTLE_TIMEOUT = 1236;
export const ERROR_ARANGO_COLLECTION_TYPE_MISMATCH = 1237;
export const ERROR_ARANGO_COLLECTION_NOT_LOADED = 1238;
export const ERROR_ARANGO_DOCUMENT_REV_BAD = 1239;

// Checked ArangoDB storage errors
// For errors that occur but are anticipated.
export const ERROR_ARANGO_DATAFILE_FULL = 1300;
export const ERROR_ARANGO_EMPTY_DATADIR = 1301;
export const ERROR_ARANGO_TRY_AGAIN = 1302;
export const ERROR_ARANGO_BUSY = 1303;
export const ERROR_ARANGO_MERGE_IN_PROGRESS = 1304;
export const ERROR_ARANGO_IO_ERROR = 1305;

// ArangoDB replication errors
export const ERROR_REPLICATION_NO_RESPONSE = 1400;
export const ERROR_REPLICATION_INVALID_RESPONSE = 1401;
export const ERROR_REPLICATION_MASTER_ERROR = 1402;
export const ERROR_REPLICATION_MASTER_INCOMPATIBLE = 1403;
export const ERROR_REPLICATION_MASTER_CHANGE = 1404;
export const ERROR_REPLICATION_LOOP = 1405;
export const ERROR_REPLICATION_UNEXPECTED_MARKER = 1406;
export const ERROR_REPLICATION_INVALID_APPLIER_STATE = 1407;
export const ERROR_REPLICATION_UNEXPECTED_TRANSACTION = 1408;
export const ERROR_REPLICATION_INVALID_APPLIER_CONFIGURATION = 1410;
export const ERROR_REPLICATION_RUNNING = 1411;
export const ERROR_REPLICATION_APPLIER_STOPPED = 1412;
export const ERROR_REPLICATION_NO_START_TICK = 1413;
export const ERROR_REPLICATION_START_TICK_NOT_PRESENT = 1414;
export const ERROR_REPLICATION_WRONG_CHECKSUM = 1416;
export const ERROR_REPLICATION_SHARD_NONEMPTY = 1417;

// ArangoDB cluster errors
export const ERROR_CLUSTER_NO_AGENCY = 1450;
export const ERROR_CLUSTER_NO_COORDINATOR_HEADER = 1451;
export const ERROR_CLUSTER_COULD_NOT_LOCK_PLAN = 1452;
export const ERROR_CLUSTER_COLLECTION_ID_EXISTS = 1453;
export const ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION_IN_PLAN = 1454;
export const ERROR_CLUSTER_COULD_NOT_READ_CURRENT_VERSION = 1455;
export const ERROR_CLUSTER_COULD_NOT_CREATE_COLLECTION = 1456;
export const ERROR_CLUSTER_TIMEOUT = 1457;
export const ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_PLAN = 1458;
export const ERROR_CLUSTER_COULD_NOT_REMOVE_COLLECTION_IN_CURRENT = 1459;
export const ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE_IN_PLAN = 1460;
export const ERROR_CLUSTER_COULD_NOT_CREATE_DATABASE = 1461;
export const ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_PLAN = 1462;
export const ERROR_CLUSTER_COULD_NOT_REMOVE_DATABASE_IN_CURRENT = 1463;
export const ERROR_CLUSTER_SHARD_GONE = 1464;
export const ERROR_CLUSTER_CONNECTION_LOST = 1465;
export const ERROR_CLUSTER_MUST_NOT_SPECIFY_KEY = 1466;
export const ERROR_CLUSTER_GOT_CONTRADICTING_ANSWERS = 1467;
export const ERROR_CLUSTER_NOT_ALL_SHARDING_ATTRIBUTES_GIVEN = 1468;
export const ERROR_CLUSTER_MUST_NOT_CHANGE_SHARDING_ATTRIBUTES = 1469;
export const ERROR_CLUSTER_UNSUPPORTED = 1470;
export const ERROR_CLUSTER_ONLY_ON_COORDINATOR = 1471;
export const ERROR_CLUSTER_READING_PLAN_AGENCY = 1472;
export const ERROR_CLUSTER_COULD_NOT_TRUNCATE_COLLECTION = 1473;
export const ERROR_CLUSTER_AQL_COMMUNICATION = 1474;
export const ERROR_ARANGO_DOCUMENT_NOT_FOUND_OR_SHARDING_ATTRIBUTES_CHANGED = 1475;
export const ERROR_CLUSTER_COULD_NOT_DETERMINE_ID = 1476;
export const ERROR_CLUSTER_ONLY_ON_DBSERVER = 1477;
export const ERROR_CLUSTER_BACKEND_UNAVAILABLE = 1478;
export const ERROR_CLUSTER_UNKNOWN_CALLBACK_ENDPOINT = 1479;
export const ERROR_CLUSTER_AGENCY_STRUCTURE_INVALID = 1480;
export const ERROR_CLUSTER_AQL_COLLECTION_OUT_OF_SYNC = 1481;
export const ERROR_CLUSTER_COULD_NOT_CREATE_INDEX_IN_PLAN = 1482;
export const ERROR_CLUSTER_COULD_NOT_DROP_INDEX_IN_PLAN = 1483;
export const ERROR_CLUSTER_CHAIN_OF_DISTRIBUTESHARDSLIKE = 1484;
export const ERROR_CLUSTER_MUST_NOT_DROP_COLL_OTHER_DISTRIBUTESHARDSLIKE = 1485;
export const ERROR_CLUSTER_UNKNOWN_DISTRIBUTESHARDSLIKE = 1486;
export const ERROR_CLUSTER_INSUFFICIENT_DBSERVERS = 1487;
export const ERROR_CLUSTER_COULD_NOT_DROP_FOLLOWER = 1488;
export const ERROR_CLUSTER_SHARD_LEADER_REFUSES_REPLICATION = 1489;
export const ERROR_CLUSTER_SHARD_FOLLOWER_REFUSES_OPERATION = 1490;
export const ERROR_CLUSTER_SHARD_LEADER_RESIGNED = 1491;
export const ERROR_CLUSTER_AGENCY_COMMUNICATION_FAILED = 1492;
export const ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_REPLICATION_FACTOR = 1493;
export const ERROR_CLUSTER_DISTRIBUTE_SHARDS_LIKE_NUMBER_OF_SHARDS = 1494;
export const ERROR_CLUSTER_LEADERSHIP_CHALLENGE_ONGOING = 1495;
export const ERROR_CLUSTER_NOT_LEADER = 1496;
export const ERROR_CLUSTER_COULD_NOT_CREATE_VIEW_IN_PLAN = 1497;
export const ERROR_CLUSTER_VIEW_ID_EXISTS = 1498;
export const ERROR_CLUSTER_COULD_NOT_DROP_COLLECTION = 1499;

// ArangoDB query errors
export const ERROR_QUERY_KILLED = 1500;
export const ERROR_QUERY_PARSE = 1501;
export const ERROR_QUERY_EMPTY = 1502;
export const ERROR_QUERY_SCRIPT = 1503;
export const ERROR_QUERY_NUMBER_OUT_OF_RANGE = 1504;
export const ERROR_QUERY_INVALID_GEO_VALUE = 1505;
export const ERROR_QUERY_VARIABLE_NAME_INVALID = 1510;
export const ERROR_QUERY_VARIABLE_REDECLARED = 1511;
export const ERROR_QUERY_VARIABLE_NAME_UNKNOWN = 1512;
export const ERROR_QUERY_COLLECTION_LOCK_FAILED = 1521;
export const ERROR_QUERY_TOO_MANY_COLLECTIONS = 1522;
export const ERROR_QUERY_DOCUMENT_ATTRIBUTE_REDECLARED = 1530;
export const ERROR_QUERY_FUNCTION_NAME_UNKNOWN = 1540;
export const ERROR_QUERY_FUNCTION_ARGUMENT_NUMBER_MISMATCH = 1541;
export const ERROR_QUERY_FUNCTION_ARGUMENT_TYPE_MISMATCH = 1542;
export const ERROR_QUERY_INVALID_REGEX = 1543;
export const ERROR_QUERY_BIND_PARAMETERS_INVALID = 1550;
export const ERROR_QUERY_BIND_PARAMETER_MISSING = 1551;
export const ERROR_QUERY_BIND_PARAMETER_UNDECLARED = 1552;
export const ERROR_QUERY_BIND_PARAMETER_TYPE = 1553;
export const ERROR_QUERY_INVALID_LOGICAL_VALUE = 1560;
export const ERROR_QUERY_INVALID_ARITHMETIC_VALUE = 1561;
export const ERROR_QUERY_DIVISION_BY_ZERO = 1562;
export const ERROR_QUERY_ARRAY_EXPECTED = 1563;
export const ERROR_QUERY_FAIL_CALLED = 1569;
export const ERROR_QUERY_GEO_INDEX_MISSING = 1570;
export const ERROR_QUERY_FULLTEXT_INDEX_MISSING = 1571;
export const ERROR_QUERY_INVALID_DATE_VALUE = 1572;
export const ERROR_QUERY_MULTI_MODIFY = 1573;
export const ERROR_QUERY_INVALID_AGGREGATE_EXPRESSION = 1574;
export const ERROR_QUERY_COMPILE_TIME_OPTIONS = 1575;
export const ERROR_QUERY_EXCEPTION_OPTIONS = 1576;
export const ERROR_QUERY_DISALLOWED_DYNAMIC_CALL = 1578;
export const ERROR_QUERY_ACCESS_AFTER_MODIFICATION = 1579;

// AQL user function errors
export const ERROR_QUERY_FUNCTION_INVALID_NAME = 1580;
export const ERROR_QUERY_FUNCTION_INVALID_CODE = 1581;
export const ERROR_QUERY_FUNCTION_NOT_FOUND = 1582;
export const ERROR_QUERY_FUNCTION_RUNTIME_ERROR = 1583;

// AQL query registry errors
export const ERROR_QUERY_BAD_JSON_PLAN = 1590;
export const ERROR_QUERY_NOT_FOUND = 1591;
export const ERROR_QUERY_IN_USE = 1592;

export const ERROR_QUERY_USER_ASSERT = 1593;
export const ERROR_QUERY_USER_WARN = 1594;

// ArangoDB cursor errors
export const ERROR_CURSOR_NOT_FOUND = 1600;
export const ERROR_CURSOR_BUSY = 1601;

// ArangoDB transaction errors
export const ERROR_TRANSACTION_INTERNAL = 1650;
export const ERROR_TRANSACTION_NESTED = 1651;
export const ERROR_TRANSACTION_UNREGISTERED_COLLECTION = 1652;
export const ERROR_TRANSACTION_DISALLOWED_OPERATION = 1653;
export const ERROR_TRANSACTION_ABORTED = 1654;

// User management errors
export const ERROR_USER_INVALID_NAME = 1700;
export const ERROR_USER_INVALID_PASSWORD = 1701;
export const ERROR_USER_DUPLICATE = 1702;
export const ERROR_USER_NOT_FOUND = 1703;
export const ERROR_USER_CHANGE_PASSWORD = 1704;
export const ERROR_USER_EXTERNAL = 1705;

// Service management errors (legacy)
// These have been superceded by the Foxx management errors in public APIs.
export const ERROR_SERVICE_INVALID_NAME = 1750;
export const ERROR_SERVICE_INVALID_MOUNT = 1751;
export const ERROR_SERVICE_DOWNLOAD_FAILED = 1752;
export const ERROR_SERVICE_UPLOAD_FAILED = 1753;

// LDAP errors
export const ERROR_LDAP_CANNOT_INIT = 1800;
export const ERROR_LDAP_CANNOT_SET_OPTION = 1801;
export const ERROR_LDAP_CANNOT_BIND = 1802;
export const ERROR_LDAP_CANNOT_UNBIND = 1803;
export const ERROR_LDAP_CANNOT_SEARCH = 1804;
export const ERROR_LDAP_CANNOT_START_TLS = 1805;
export const ERROR_LDAP_FOUND_NO_OBJECTS = 1806;
export const ERROR_LDAP_NOT_ONE_USER_FOUND = 1807;
export const ERROR_LDAP_USER_NOT_IDENTIFIED = 1808;
export const ERROR_LDAP_INVALID_MODE = 1820;

// Task errors
export const ERROR_TASK_INVALID_ID = 1850;
export const ERROR_TASK_DUPLICATE_ID = 1851;
export const ERROR_TASK_NOT_FOUND = 1852;

// Graph / traversal errors
export const ERROR_GRAPH_INVALID_GRAPH = 1901;
export const ERROR_GRAPH_COULD_NOT_CREATE_GRAPH = 1902;
export const ERROR_GRAPH_INVALID_VERTEX = 1903;
export const ERROR_GRAPH_COULD_NOT_CREATE_VERTEX = 1904;
export const ERROR_GRAPH_COULD_NOT_CHANGE_VERTEX = 1905;
export const ERROR_GRAPH_INVALID_EDGE = 1906;
export const ERROR_GRAPH_COULD_NOT_CREATE_EDGE = 1907;
export const ERROR_GRAPH_COULD_NOT_CHANGE_EDGE = 1908;
export const ERROR_GRAPH_TOO_MANY_ITERATIONS = 1909;
export const ERROR_GRAPH_INVALID_FILTER_RESULT = 1910;
export const ERROR_GRAPH_COLLECTION_MULTI_USE = 1920;
export const ERROR_GRAPH_COLLECTION_USE_IN_MULTI_GRAPHS = 1921;
export const ERROR_GRAPH_CREATE_MISSING_NAME = 1922;
export const ERROR_GRAPH_CREATE_MALFORMED_EDGE_DEFINITION = 1923;
export const ERROR_GRAPH_NOT_FOUND = 1924;
export const ERROR_GRAPH_DUPLICATE = 1925;
export const ERROR_GRAPH_VERTEX_COL_DOES_NOT_EXIST = 1926;
export const ERROR_GRAPH_WRONG_COLLECTION_TYPE_VERTEX = 1927;
export const ERROR_GRAPH_NOT_IN_ORPHAN_COLLECTION = 1928;
export const ERROR_GRAPH_COLLECTION_USED_IN_EDGE_DEF = 1929;
export const ERROR_GRAPH_EDGE_COLLECTION_NOT_USED = 1930;
export const ERROR_GRAPH_NO_GRAPH_COLLECTION = 1932;
export const ERROR_GRAPH_INVALID_EXAMPLE_ARRAY_OBJECT_STRING = 1933;
export const ERROR_GRAPH_INVALID_EXAMPLE_ARRAY_OBJECT = 1934;
export const ERROR_GRAPH_INVALID_NUMBER_OF_ARGUMENTS = 1935;
export const ERROR_GRAPH_INVALID_PARAMETER = 1936;
export const ERROR_GRAPH_INVALID_ID = 1937;
export const ERROR_GRAPH_COLLECTION_USED_IN_ORPHANS = 1938;
export const ERROR_GRAPH_EDGE_COL_DOES_NOT_EXIST = 1939;
export const ERROR_GRAPH_EMPTY = 1940;
export const ERROR_GRAPH_INTERNAL_DATA_CORRUPT = 1941;
export const ERROR_GRAPH_INTERNAL_EDGE_COLLECTION_ALREADY_SET = 1942;
export const ERROR_GRAPH_CREATE_MALFORMED_ORPHAN_LIST = 1943;
export const ERROR_GRAPH_EDGE_DEFINITION_IS_DOCUMENT = 1944;

// Session errors
export const ERROR_SESSION_UNKNOWN = 1950;
export const ERROR_SESSION_EXPIRED = 1951;

// Simple Client errors
export const SIMPLE_CLIENT_UNKNOWN_ERROR = 2000;
export const SIMPLE_CLIENT_COULD_NOT_CONNECT = 2001;
export const SIMPLE_CLIENT_COULD_NOT_WRITE = 2002;
export const SIMPLE_CLIENT_COULD_NOT_READ = 2003;

// Communicator errors
export const COMMUNICATOR_REQUEST_ABORTED = 2100;
export const COMMUNICATOR_DISABLED = 2101;

// Foxx management errors
export const ERROR_MALFORMED_MANIFEST_FILE = 3000;
export const ERROR_INVALID_SERVICE_MANIFEST = 3001;
export const ERROR_SERVICE_FILES_MISSING = 3002;
export const ERROR_SERVICE_FILES_OUTDATED = 3003;
export const ERROR_INVALID_FOXX_OPTIONS = 3004;
export const ERROR_INVALID_MOUNTPOINT = 3007;
export const ERROR_SERVICE_NOT_FOUND = 3009;
export const ERROR_SERVICE_NEEDS_CONFIGURATION = 3010;
export const ERROR_SERVICE_MOUNTPOINT_CONFLICT = 3011;
export const ERROR_SERVICE_MANIFEST_NOT_FOUND = 3012;
export const ERROR_SERVICE_OPTIONS_MALFORMED = 3013;
export const ERROR_SERVICE_SOURCE_NOT_FOUND = 3014;
export const ERROR_SERVICE_SOURCE_ERROR = 3015;
export const ERROR_SERVICE_UNKNOWN_SCRIPT = 3016;

// JavaScript module loader errors
export const ERROR_MODULE_NOT_FOUND = 3100;
export const ERROR_MODULE_SYNTAX_ERROR = 3101;
export const ERROR_MODULE_FAILURE = 3103;

// Enterprise errors
export const ERROR_NO_SMART_COLLECTION = 4000;
export const ERROR_NO_SMART_GRAPH_ATTRIBUTE = 4001;
export const ERROR_CANNOT_DROP_SMART_COLLECTION = 4002;
export const ERROR_KEY_MUST_BE_PREFIXED_WITH_SMART_GRAPH_ATTRIBUTE = 4003;
export const ERROR_ILLEGAL_SMART_GRAPH_ATTRIBUTE = 4004;
export const ERROR_SMART_GRAPH_ATTRIBUTE_MISMATCH = 4005;

// Cluster repair errors
export const ERROR_CLUSTER_REPAIRS_FAILED = 5000;
export const ERROR_CLUSTER_REPAIRS_NOT_ENOUGH_HEALTHY = 5001;
export const ERROR_CLUSTER_REPAIRS_REPLICATION_FACTOR_VIOLATED = 5002;
export const ERROR_CLUSTER_REPAIRS_NO_DBSERVERS = 5003;
export const ERROR_CLUSTER_REPAIRS_MISMATCHING_LEADERS = 5004;
export const ERROR_CLUSTER_REPAIRS_MISMATCHING_FOLLOWERS = 5005;
export const ERROR_CLUSTER_REPAIRS_INCONSISTENT_ATTRIBUTES = 5006;
export const ERROR_CLUSTER_REPAIRS_MISMATCHING_SHARDS = 5007;
export const ERROR_CLUSTER_REPAIRS_JOB_FAILED = 5008;
export const ERROR_CLUSTER_REPAIRS_JOB_DISAPPEARED = 5009;
export const ERROR_CLUSTER_REPAIRS_OPERATION_FAILED = 5010;

// Agency errors
export const ERROR_AGENCY_INQUIRY_SYNTAX = 20001;
export const ERROR_AGENCY_INFORM_MUST_BE_OBJECT = 20011;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_TERM = 20012;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_ID = 20013;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_ACTIVE = 20014;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_POOL = 20015;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_MIN_PING = 20016;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_MAX_PING = 20017;
export const ERROR_AGENCY_INFORM_MUST_CONTAIN_TIMEOUT_MULT = 20018;
export const ERROR_AGENCY_INQUIRE_CLIENT_ID_MUST_BE_STRING = 20020;
export const ERROR_AGENCY_CANNOT_REBUILD_DBS = 20021;

// Supervision errors
export const ERROR_SUPERVISION_GENERAL_FAILURE = 20501;

// Dispatcher errors
export const ERROR_DISPATCHER_IS_STOPPING = 21001;
export const ERROR_QUEUE_UNKNOWN = 21002;
export const ERROR_QUEUE_FULL = 21003;

// Maintenance errors
export const ERROR_ACTION_ALREADY_REGISTERED = 6001;
export const ERROR_ACTION_OPERATION_UNABORTABLE = 6002;
export const ERROR_ACTION_UNFINISHED = 6003;
export const ERROR_NO_SUCH_ACTION = 6004;
