image: node:latest

cache:
  paths:
    - node_modules/
    - arangodb

stages:
  - test

test:
  stage: test
  script:
    - mkdir -p arangodb && cd arangodb && curl -L https://download.arangodb.com/travisCI/setup_arangodb_3.2.4.sh | bash
    - npm install
    - npm test:coverage
    - npm run test:dropdb
