image: node:latest

cache:
  paths:
    - node_modules/
    - arangodb

stages:
 - test
 - deploy

test:
  stage: test
  script:
    - mkdir -p arangodb && cd arangodb && curl -L https://download.arangodb.com/travisCI/setup_arangodb_3.2.4.sh | bash
    - npm install
    - npm run test:coverage
    - npm run test:dropdb

deploy-npm:
  stage: deploy
  script:
    - npm install
    - npm publish
  #only:
  #  - /^release-.*$/
  when: manual
