language: node_js
node_js:
  - "8"
install:
  - npm ci
script:
  - mkdir -p arangodb && cd arangodb && curl -L https://download.arangodb.com/travisCI/setup_arangodb_3.2.4.sh | bash
  - npm run test:coverage
  - npm run test:dropdb
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"