language: node_js
node_js:
- '8'
script:
- mkdir -p arangodb && cd arangodb && curl -L https://download.arangodb.com/travisCI/setup_arangodb_3.2.4.sh
  | bash
- npm install
- npm run test:coverage
- npm run test:dropdb
deploy:
  provider: npm
  email: "Nils.Wenzler@aeb.com"
  tag: next
  deploy.skip_cleanup: true
  api_key:
    secure: K2vmhlh3TEViTNsQndaDyUCLhciw4Lej7vtjerjLCcuoqoiTz5QM0Kd4vIiT9TD/RCdVeetoES7x0meZ5MLDbDNPEGakSFy3D+Y69LvV+7anf7eZKxWMASAOunrI+GOjvgMcawyp8U47KeLdMWZqukaHYQcli6kadtbdGuiJTYY5M1MbJZUIxACGGJurCCW09Mk2klvjUyPDBs17hdpYNEAdj7XXPe7cvBT9yqwjHUamZEYsgvJ9Z60MznIMm0PC5wNzwxyLTTmxQ7bQ38CMzjLiDJzwpV9dA8YXYTxur2QpmY1cp7tRTX6Rf6teHjA6b5VdEMgI8WHM/86rftsPJVInPFeFPttjJLqygvalv5/Yyn6W8H7/YYd+QWRCgY8DgNmjGX90ANNDq5gkWXlT8nm4t+J+FiujZCWjKImWPNjH81gEg5RLDfqJc5M9CtJoRT1PfGgY8TIRKxg3Nq2nDSGRr4+gW3BgKrpNfaxe25kMu9wgeMQKFnrG/tgEcL1hvjDf6x05St2BJAAi3qWm5SOFH9I1kD0o1/HXC8g/HDZERRhTTG1lL9O4AQAlTdM6d0fl/nupxK2IZP2VJPt6r/QmbbfG1KKB5TsgaCShIv/kwaJOfJTsbeS2q/CCcfqxa3yl87zjIHQRFrcMZpt8ghyM7NcXdXTq9Ojyo4MhSzI=
  on:
    tags: true