language: node_js
node_js:
  - '8'
env:
  matrix:
    - ARANGO_VERSION=3.2
    - ARANGO_VERSION=3.3
    - ARANGO_VERSION=3.4
before_install:
  - docker run --name arangodb -p 127.0.0.1:8529:8529 -d -e ARANGO_NO_AUTH=1 arangodb:$ARANGO_VERSION
  - timeout 10 docker logs --follow arangodb || true # wait until arangodb is started
  - curl -L http://localhost:8529/_api/version
install:
  - npm ci
script:
  - npm run test:coverage
  - npm run test:dropdb
deploy:
  - provider: npm
    email: "Nils.Wenzler@aeb.com"
    skip_cleanup: true
    tag: next # don't use "latest" default dist-tag because then prereleases would be installed with "npm install cruddl". We need to tag releases manually.
    api_key:
      secure: r3WJg7Y0K9Vp6Kyg5OYAVCULmdadLonkWqK9KwoC4ZX2t+d6VSeAJHWyz5UfIFgPSQJA5t7jJUrFqh4VEf2R4PXPbbfpBvJ4Sdxn1yrXn6Lh2hw0feao9/1LN2NJSXBIjtP164lILS3u7/HrsgFEAXz28gknLMoEbjGoJqfW2cvab4Nm6fmb6f9brWiNkD+YgGXUfnezU3O5yf1b3ZiYv6KY8TQkEafBxHY438DM7v4RplGHYNMapMK5AV74GA3+gAi4c4F1ARe+5lx528/02f7wXguN6Kt3pRcKf2sExlHBrQNmpzHBALsUygtTVIYS8P51F4Im2+j6OidbD7HiDahxSi6Bz3gvrXJ6KPO+5FdQ4+EOMfkZvbMJAnHcfduVNQOeBpblyLVGK2rFwRVDhF+qcXxci8n/wNFPKJECuGK4dMLya5P/G9hrB5tFY/FCS3jsGkfTWiKjNGINIFCExuOYyeTaGpi+FuS47HcD7yAQThQrrf8lhsMuQFbT6OXRuxro4MbURVEtJPbO7vn50KFOq2Fbg8lDUR5BiuWMAZkE4FJRsL8lfVQ+2wZ6cdWrGos9ks+lDTNgPQ/FP2u7F7L0ds7jDNbYdpDNcuaOqK9Drzd6xWCf7WfTiDM/jJi7nq8m5n5iC8YGSk0PrOXUSfIRCZKavg1GugP2W4QU9G0=
    on:
      tags: true
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
services:
  - docker
