import { expect } from 'chai';
import gql from 'graphql-tag';
import {
    calculateRequiredIndexOperations,
    getRequiredIndicesFromModel,
} from '../../../../src/database/arangodb/schema-migration/index-helpers';
import { createSimpleModel } from '../../../model/model-spec.helper';

describe('index-helpers', () => {
    it('extracts persistent and vector indices from the model', () => {
        const model = createSimpleModel(gql`
            type Product @rootEntity {
                key: String @key
                embedding: [Float!]! @vectorIndex(metric: COSINE, dimension: 768, nLists: 100)
                code: String @index
            }
        `);

        const requiredIndices = getRequiredIndicesFromModel(model);
        const vectorIndex = requiredIndices.find((index) => index.type === 'vector');
        const persistentIndex = requiredIndices.find(
            (index) => index.type === 'persistent' && index.fields.join(',') === 'code',
        );

        expect(vectorIndex).to.not.be.undefined;
        expect(vectorIndex!.type).to.equal('vector');
        expect(vectorIndex!.fields).to.deep.equal(['embedding']);
        if (vectorIndex && vectorIndex.type === 'vector') {
            expect(vectorIndex.params.metric).to.equal('cosine');
            expect(vectorIndex.params.dimension).to.equal(768);
            expect(vectorIndex.params.nLists).to.equal(100);
        }

        expect(persistentIndex).to.not.be.undefined;
    });

    it('matches unnamed required indices against existing autogenerated names', () => {
        const model = createSimpleModel(gql`
            type Product @rootEntity {
                embedding: [Float!]! @vectorIndex(metric: COSINE, dimension: 3, nLists: 10)
            }
        `);

        const requiredIndices = getRequiredIndicesFromModel(model);
        const existingIndices = requiredIndices.map((index) => ({
            ...index,
            id: 'products/1234',
            name: 'idx_1234',
        }));

        const result = calculateRequiredIndexOperations(
            existingIndices,
            requiredIndices,
            {} as any,
        );
        expect(result.indicesToCreate).to.deep.equal([]);
        expect(result.indicesToDelete).to.deep.equal([]);
    });
});
